# web port
server:
  port: 8081
spring:
  application:
    name: xxl-job-executor
# log config
logging:
  config: classpath:logback.xml



xxl:
  server:
    executor:
      ip: 192.168.159.136
      addresses: http://192.168.159.136:8982/
      log-path: /data/logs/springtest
      port: 9999
      app-name: springtest